=== HuaChenLi/AuditCodes/My Audit/Column Rules/column_rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Columns">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="IncomeColumns">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Column" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence minOccurs="0">
                                        <xs:element name="ColumnName" type="xs:string"/>
                                        <xs:element name="GSTIncluded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Y"/>
                                                    <xs:enumeration value="N"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Values" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Value" maxOccurs="unbounded"
                                                        type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ExpenseColumns">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Column" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ColumnName" type="xs:string"/>
                                        <xs:element name="GSTIncluded">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Y"/>
                                                    <xs:enumeration value="N"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Values" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Value" maxOccurs="unbounded"
                                                        type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== HuaChenLi/AuditCodes/Column Rules/everyday_offset_col_rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<Columns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="column_rules.xsd">
    <IncomeColumns>
        <Column>
            <ColumnName>Misc.</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Invoices</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Tax Refund</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>PAYMENT RECEIVED</Value>
                <Value>Mastercard Payment</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Netbank Saver</Value>
                <Value>Business Transacti</Value>
                <Value>Everyday Offset</Value>
            </Values>
        </Column>
    </IncomeColumns>
    <ExpenseColumns>
        <Column>
            <ColumnName>Misc.</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Home Loan</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Home Loan</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Mastercard</Value>
                <Value>Business Trans</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Withdrawals</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>ATM CBA ATM</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Insurance</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>AIA Australia</Value>
            </Values>
        </Column>
    </ExpenseColumns>
</Columns>

=== HuaChenLi/AuditCodes/My Audit/Column Rules/my_account_rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<Columns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="column_rules.xsd">
    <IncomeColumns>
        <Column>
            <ColumnName>Misc.</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Wages</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>Salary</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Pay me Back</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Damien</Value>
                <Value>Zhijie</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Tax Refund</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>ATO</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>xx6079</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers from Family</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>QiQiong</Value>
                <Value>Zhi Kang</Value>
                <Value>Mastercard Autopay</Value>
            </Values>
        </Column>
    </IncomeColumns>
    <ExpenseColumns>
        <Column>
            <ColumnName>With Friends</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>UBER</Value>
                <Value>MANGO</Value>
                <Value>LINDOS</Value>
                <Value>ZJ</Value>
                <Value>Bday</Value>
                <Value>Truman</Value>
                <Value>Zhijie</Value>
                <Value>Universal</Value>
                <Value>SIRDUKE</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Takeaway for Work</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>HERO SUSHI</Value>
                <Value>MIGHTY</Value>
                <Value>MCDONALDS</Value>
                <Value>ZEUS</Value>
                <Value>NOODLEBOX</Value>
                <Value>TOP NOTCH</Value>
                <Value>HUNKY DORY</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Groceries</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>WOOLWORTHS</Value>
                <Value>COLES</Value>
                <Value>CHEMWAREHS</Value>
                <Value>SUPAIGA</Value>
                <Value>KMART</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Subscriptions</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Optus</Value>
                <Value>Crunchyroll</Value>
                <Value>Spotify</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transport</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>EG GROUP</Value>
                <Value>MYKI</Value>
                <Value>TOYOTA</Value>
                <Value>EASTLINK</Value>
                <Value>PAYSTAY</Value>
                <Value>VICROADS</Value>
                <Value>7-ELEVEN</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Games</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Nintendo</Value>
            </Values>
        </Column>        
        <Column>
            <ColumnName>Merch</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Clothes</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>DAVIECLOTHI</Value>
                <Value>Uniqlo</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Tech</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>SCORPIONTEC</Value>
                <Value>OFFICEWORKS</Value>
                <Value>KOGAN</Value>
                <Value>DICKSMITH</Value>
                <Value>JB HI-FI</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>Mastercard Autopay</Value>
                <Value>xx6079</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers to Family</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>BUSINESS TRANS</Value>
                <Value>EVERYDAY OFFSET</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Business Expenditure</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>ASIC</Value>
                <Value>REPCO</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Education</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>PEGS</Value>
                <Value>CAMPION</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Family</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>GOLD LEAF</Value>
                <Value>ARLBERG</Value>
                <Value>MOUNT BULLER</Value>
                <Value>SKI HIRE</Value>
                <Value>EUROA</Value>
                <Value>FAMILY DNTL</Value>
                <Value>CENTRELINK</Value>
            </Values>
        </Column>        
        <Column>
            <ColumnName>Utilities</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Yarra Valley</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Misc.</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
    </ExpenseColumns>
</Columns>

=== HuaChenLi/AuditCodes/Business Audit/Column Rules/mastercard_col_rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<Columns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="column_rules.xsd">
    <IncomeColumns>
        <Column>
            <ColumnName>Misc.</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Invoices</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Tax Refund</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>ATO</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>PAYMENT RECEIVED</Value>
                <Value>Mastercard Payment</Value>
            </Values>
        </Column>
    </IncomeColumns>
    <ExpenseColumns>
        <Column>
            <ColumnName>Misc.</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Take Away</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>MCDONALDS</Value>
                <Value>HUNGRY JACKS</Value>
                <Value>KFC</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Tools</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>REPCO</Value>
                <Value>BUNNINGS</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>New Home</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>SPOTLIGHT</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Petrol and Toll</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>EG GROUP</Value>
                <Value>MYKI</Value>
                <Value>TOYOTA</Value>
                <Value>EASTLINK</Value>
                <Value>PAYSTAY</Value>
                <Value>VICROADS</Value>
                <Value>7-ELEVEN</Value>
                <Value>COLES</Value>
                <Value>EXPRESS</Value>
                <Value>DANDENONG</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Utilities</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>SPOTIFY</Value>
                <Value>CRUNCHYROLL</Value>
                <Value>BELONG</Value>
                <Value>OPTUS</Value>
                <Value>TANGO ENERGY</Value>
                <Value>ENERGYAUSTRALIA</Value>
                <Value>VALLEY WATER</Value>
                <Value>XERO</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Groceries</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>WOOLWORTHS</Value>
                <Value>CHEMIST WAREHOUSE</Value>
                <Value>IGA</Value>
                <Value>KMART</Value>
                <Value>ALDI</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Insurance</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>ASIC</Value>
                <Value>COMMONWEALTH INSURANCE</Value>
                <Value>ALLIANZ</Value>
                <Value>RACV</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Children</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>PEGS</Value>
                <Value>CAMPION</Value>
                <Value>ALLISON BROWNING</Value>
                <Value>PENLEIGH</Value>
                <Value>HEALTHY PETS</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Holiday</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>GOLD LEAF</Value>
                <Value>ARLBERG</Value>
                <Value>MOUNT BULLER</Value>
                <Value>SKI HIRE</Value>
                <Value>EUROA</Value>
                <Value>FAMILY DNTL</Value>
                <Value>CENTRELINK</Value>
            </Values>
        </Column>
    </ExpenseColumns>
</Columns>

=== HuaChenLi/AuditCodes/Business Audit/Column Rules/business_transaction_account_col_rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<Columns xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="column_rules.xsd">
    <IncomeColumns>
        <Column>
            <ColumnName>Misc.</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Invoices</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>Everkeen</Value>
                <Value>DONG LENG</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Tax Refund</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>ATO</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Netbank Everyday Offset</Value>
            </Values>
        </Column>
    </IncomeColumns>
    <ExpenseColumns>
        <Column>
            <ColumnName>Misc. without GST</ColumnName>
            <GSTIncluded>N</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Subcontract</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Wages</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Qi Qiong</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>New Home</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Insurance</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
        </Column>
        <Column>
            <ColumnName>Taxes and Super</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>REF108124249</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Accounting Fees</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>FinTax Solutions</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Transfers</ColumnName>
            <GSTIncluded>N</GSTIncluded>
            <Values>
                <Value>Mastercard</Value>
                <Value>Everyday Offset</Value>
            </Values>
        </Column>
        <Column>
            <ColumnName>Misc. with GST</ColumnName>
            <GSTIncluded>Y</GSTIncluded>
            <Values>
                <Value>Optus</Value>
            </Values>
        </Column>
    </ExpenseColumns>
</Columns>
